apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopstest
  name: devopstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopstest
  strategy: {}
  template:
    metadata:
      labels:
        app: devopstest
    spec:
      #restartPolicy: Never
      containers:
      - image: prageeth1985/devopstest:20221207-1106
        name: devopstest
        #command:
        #  - "/bin/sh"
        #  - "-c"
        #  - "env"
        resources: {}
        env:
          - name: pathurl #name of the environment variable we are going to create inside pod
            valueFrom:
              configMapKeyRef:
                key: testurl #which key to use extract the respective value from configmap, then that value is assigned to pathurl environment variable
                name: cmtest #name of the configmap