apiVersion: v1
kind: Service
metadata:
  name: devopstest
  #namespace: default
spec:
  selector:
    app: devopstest
  type: LoadBalancer
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: devopstest
    protocol: TCP
    port: 80
    targetPort: 7000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
